### ISSUE TITLE
Update CONTRIBUTING.md examples.

### ISSUE THREAD

**Issue by jamen** [PoweredRails/Rails#14]
The [`CONTRIBUTING.md`](https://github.com/PoweredRails/Rails/blob/837d9614dcfcad844e8f1c2a60d99dda470363cf/CONTRIBUTING.MD) file has `"Apache Licensing"` at the top.  I'm not sure if this is because you were previously using Apache's license, or if you had copied and pasted the example from somewhere (Google's styleguide perhaps).  But it's a bit misleading.

**Comment by JamenMarz** [comment]
I can make a PR, give me a sec.

**Comment by JamenMarz** [comment]
Also, wasn't it ruled that you weren't going to use minimal interfaces? So the interfaces example is kinda redundant.  They could just follow the same style based on the class example.

**Comment by ConnorHartley** [comment]
The contributors file is missing a lot of information. I will work on updating it.

**Comment by ConnorHartley** [comment]
Added some changes to the Contributors file. This will probably be moved to the documentation later on.
