### ISSUE TITLE
Branch clean up and protection

### ISSUE THREAD

**Issue by jamen** [PoweredRails/Rails#17]
1. The `jacklin213-checkstyle` branch was for [merging fixes upstream from a fork](https://github.com/PoweredRails/Rails/pull/9).  Now that it's merged it doesn't seem to have any significance on it's own because it's 0 commits ahead of the master branch. I believe it should be deleted.

2. Protect the `master`, that way it can't be deleted, people can't force push, and **can't be merged until status checks pass**. <sub>[More info on Protected Branches](https://help.github.com/articles/about-protected-branches/)</sub>

**Comment by jacklin213** [comment]
```master``` will not be protected due to the need to force push in case we need to rewrite history, I'll have my branch deleted
