### ISSUE TITLE
Set up some milestones.

### ISSUE THREAD

**Issue by jamen** [PoweredRails/Rails#43]
You guys have a version map which is great.  I think you should automate it into GitHub milestones now.  I recently saw someone structuring their application planning like this, and I think it's a really good method to go about tracking progress as well as letting people know what needs to be worked on...

You can "bind" multiple GitHub issues under a Milestone to reach, for example, [I have done this with my project Pheo](https://github.com/jamen/pheo/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A%22minimum+viable+product%22+).  Helpful for setting goals to reach that can be tracked under a more simplified system (automated by GitHub)...  It's also visually easier to see progress ([an example with Pheo again](https://github.com/jamen/pheo/milestones)).

Not only issues can be bound to milestones either.  You can also put pull requests under a milestone, this makes tracking progress even more nice for contributions.

I think it's something you guys should consider, it makes it easier for team members and outsiders to visually see progress, it also helps organize it.

**Comment by ConnorHartley** [comment]
Sounds like a great idea! We'll look into this more.

**Comment by iLexiconn** [comment]
Did some kind of thing. Just make issues for every feature we need for the milestone.

**Comment by jamen** [comment]
It's good we made milestones, but we need to open issues for them! ;P
