### ISSUE TITLE
Build error (and setup script error).

### ISSUE THREAD

**Issue by JamenMarz** [PoweredRails/Rails#8]
I know this is still in planning / early development stages...  But I simply running build it and recieved an error...

> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/home/jamen/projects/Rails/gradle/extended/buildscripts/project.gradle' line: 7
> 
> * What went wrong:
> A problem occurred evaluating script.
> > Could not read script > '/home/jamen/projects/Rails/RailsAPI/gradle/extended/buildscripts/project.gradle' as it does not exist.

I believe this is simply an error due to how Git clones projects.  When cloning, the `RailsAPI` folder (submodule on GitHub) is empty, therefore the necessary material cannot be found.

I don't know Java and Gradle that well, but you might want to add the RailsAPI as a dependency in Gradle, instead of as a sub-module in the repository.

**Comment by JamenMarz** [comment]
Sorry, not a build error, I mean the setup script.

**Comment by JamenMarz** [comment]
Oh damn, I have gradle 1.4, let me update to 2.4 and test again.

**Comment by JamenMarz** [comment]
Actually, I tried building as well.  This problem seems to be on both.

**Comment by JamenMarz** [comment]
Never mind, it appears that the convention for Java projects on GitHub is included with the sub-module structure.  It can simply be fixed by running the following command to fetch the sub-module resources:

```
git submodule init
```

**Comment by jacklin213** [comment]
```git submodule update --init --recursive```

Would be a better way to do this
